steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$cog01j3qdy6xns3g9fzvsjz14by1v/streamlit-app:latest', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'streamlit-app', '--image', 'gcr.io/$cog01j3qdy6xns3g9fzvsjz14by1v/streamlit-app:latest']
 
images:
- name: gcr.io/$cog01j3qdy6xns3g9fzvsjz14by1v/streamlit-app:latest

options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://your-logs-bucket
