steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app:latest', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'streamlit-app', '--image', 'gcr.io/$PROJECT_ID/streamlit-app:latest']

images:
  - 'gcr.io/$PROJECT_ID/streamlit-app:latest'


